name = "TermLayouts"
uuid = "db71dc42-8c32-4818-866d-c72779f4e569"
authors = ["Soumitra Shewale <soumitra.shewale.dev@gmail.com>"]
version = "0.1.0"

[deps]
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
